#!/usr/bin/env node
/**
 * Interactive setup script for server .env configuration
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const envPath = path.join(__dirname, '.env');
const envExamplePath = path.join(__dirname, '.env.example');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function setup() {
    console.log('🔧 MySQL Server Configuration Setup\n');
    console.log('Please provide your MySQL connection details:\n');

    // Check if .env already exists
    if (fs.existsSync(envPath)) {
        const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
        if (overwrite.toLowerCase() !== 'y') {
            console.log('❌ Setup cancelled.');
            rl.close();
            return;
        }
    }

    const host = await question('MySQL Host (default: localhost): ') || 'localhost';
    const port = await question('MySQL Port (default: 3306): ') || '3306';
    const user = await question('MySQL Username (default: root): ') || 'root';
    const password = await question('MySQL Password: ');
    const database = await question('Database Name (default: tag_database): ') || 'tag_database';
    const serverPort = await question('Server Port (default: 3002): ') || '3002';

    if (!password) {
        console.log('⚠️  Warning: No password provided. Make sure MySQL allows empty passwords.');
    }

    // Build connection string
    const connectionString = `mysql://${user}:${password}@${host}:${port}/${database}`;

    // Create .env content
    const envContent = `# MySQL Database Configuration
# Generated by setup script

# Connection String (recommended)
MYSQL_CONNECTION_STRING=${connectionString}

# Alternative: Individual Parameters
# MYSQL_HOST=${host}
# MYSQL_PORT=${port}
# MYSQL_USER=${user}
# MYSQL_PASSWORD=${password}
# MYSQL_DATABASE=${database}

# Server Configuration
PORT=${serverPort}
`;

    // Write .env file
    fs.writeFileSync(envPath, envContent);

    console.log('\n✅ Configuration saved to server/.env');
    console.log(`\n📋 Connection String: mysql://${user}:***@${host}:${port}/${database}`);
    console.log('\n📝 Next steps:');
    console.log('1. Make sure MySQL server is running');
    console.log('2. Create database: CREATE DATABASE ' + database + ';');
    console.log('3. Import SQL file: mysql -u ' + user + ' -p ' + database + ' < ../tag-database-mysql.sql');
    console.log('4. Start server: yarn dev\n');

    rl.close();
}

setup().catch((error) => {
    console.error('❌ Setup failed:', error);
    rl.close();
    process.exit(1);
});


